drosalys_pdf:
  chrome_bin: '%env(CHROME_BIN)%'
  asset_output_path: '%kernel.project_dir%/public/'
  pdfTmpDir: '%kernel.cache_dir%/pdf_tmp/'
#  default_templates_dir: '%kernel.project_dir%/test'
#  default_cache_dir: '%kernel.project_dir%/var/cache/pdf'
